[package]
name = "tanu-allure-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tanu-allure = { path = ".." }
tanu = { git = "https://github.com/tanu-rs/tanu.git", branch = "grpc", features = ["grpc", "json"] }
tokio = { version = "1", features = ["full"] }
