[package]
name = "tanu-allure-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tanu-allure = { path = ".." }
tanu = { version = ">=0.17.0", features = ["grpc", "json"] }
tokio = { version = "1", features = ["full"] }
