[[projects]]
name = "docker"
test_ignore = ["tanu_integration_tests::task_local::spawned_task_without_scope_current_panics"]
retry.count = 3
retry.min_delay = "100ms"

[[projects]]
name = "httpbin.org"
base_url = "https://httpbin.org"
test_ignore = ["tanu_integration_tests::task_local::spawned_task_without_scope_current_panics"]
retry.count = 0
